using VehicleManagementConsole._1._ClassAndObjects;
using VehicleManagementConsole.Encapsulation;
using VehicleManagementConsole.Inheritance;
using VehicleManagementConsole.Polymorphism;

ClassesAndObjectServices.RunClassesAndObjectServices();
EncapsulatedService.RunEncapsulatedService();
InheritanceService.RunInheritanceService();
PolymorphismService.RunPolymorphismService();